sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CwlywU7QCdCACo4OJ9xYdba5c1V9dbTodPoha6R/YuxiIUkGBcKtT/ihHah9Hn5YBCwI/g7XgswF2z5dl6hV4sQSUrp3VImQJG1pk0j+NP4NaKmOk8COfd8mJCFw5Xuo0Nobo8xSxXzMIsRl2qpnSfY/55O8ks3IHaA+kV74kEizXuChAJYuAQp5hDsfvONSrCCQvhRtjpCv5SxZTJcNnLsT25MvFEoXJqprsCsb+srmRswTtXEYEgRcH/NXV8RbmRK/+rK9YsAB+sKDaa/nWJC4jMKwNfj9A8L8MQDWnxcgAmfVvR9asloFnV/I34VN8hQkFvUu2YQqdZBxAf8yU5on47djEm2cPX4IbYfBnnHESCffbPSLqJQbSGbxoBprkNig2Hjk8SHr51DoVoYkYIr/9gN6GXhHO/PFFJWIEP6zgp3x6TlRj1UtGnGzD0LWga/JacltizqqqI5hjpfHF5kAhwcPmQ8Hf1vA90th4CpD49aMlPR/DiOG79/QbmHjDnw/5OlUNlnoG0Xh0WQzJboj0PC4WqFamM1t4UB64a54zwBozUSc6u/jQcPj20A9oIBzyNbuH+MkjqAyzG/N82YvTwdDcdjQT3NmBFoLLHHQPMF2Rwp3RzmJrAxwLnmOMEModnxHih2PSweyLxk0xRkHhvbL8jZVsEv+1jeamuk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Bride-of-the-Nile-Volume-09_5525
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy